// This file overrides the built-in C++ (simple) runner
// For more information see http://docs.c9.io:8080/#!/api/run-method-run
{
  "script": [
    "set -e",
    "cd $scons_path",
    "scons",
    "chmod 755 $prog_path",
    "node $HOME/.c9/bin/c9gdbshim.js $prog_path -g=gdb"
  ],
  "info": "Running sudoku",
  "debugger": "gdb",
  "$debugDefaultState": false,
  "env": {},
  "selector": "^.*\\.(cpp|cc)$"
}