import fnmatch
import os

source_files = []
path_to_src = '../../src/'
patterns = ['*.cpp','*.h']

for root, dirnames, filenames in os.walk(path_to_src):
  for pattern in patterns:
    for filename in fnmatch.filter(filenames, pattern):
      source_files.append(os.path.join(root[len(path_to_src):], filename))
      
print(source_files)

# Create environment, tell SCons to look in the 'include' directoy for any files
# included by C source files
env = Environment(CPPPATH=['include'])
env.Append(CXXFLAGS = ["-ggdb","-std=c++11"])
env.Program('sudoku', source_files)
env.StaticLibrary('sudoku', source_files)